### ISSUE TITLE
Refactor: (main) Layout 분리

### ISSUE THREAD

**Issue by yeomin4242** [Usic-Room/FE#35]
## 어떤 기능인가요?
(main)도메인에서 전반적인 레이아웃 구조 리팩토링 및 사소한 Style 변경
> 추가하려는 기능에 대해 간결하게 설명해주세요

## 작업 상세 내용

- [x] Footer 고정 해제
- [x] (main) Layout Components 분리

**Comment by mixsung** [comment]
footer 제가 이번 pr에 그냥 삭제해버렸는데 다시 쓰셔도 됩니다 ^^.. 아직 footer 쓸 일이 없어서 나중에 넣어도 되지 않을까 라는 생각으로 일단 지워놨어요

**Comment by yeomin4242** [comment]
아하 저저번에 얘기했던 내용중에 있길래 추가했는데 알겠습니다~
